language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements/development.txt
# command to run tests
script:
  - flake8
  - mypy .
