language: python

matrix:
  fast_finish: true
  include:
    - python: "3.8"
    - python: "3.9"
    - python: "3.10"
    - python: "3.11"
# command to install dependencies
install:
  - pip install -r requirements/development.txt
# command to run tests
script:
  - python --version
  - flake8 --version
  - flake8
  - mypy --version
  - mypy .
